title = "gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "Amplify allow list"
paths = [
    '''team-provider-info.json'''
]

[[rules]]
id = "hashicorp-tf-password-singlequote"
description = "Identified a HashiCorp Terraform password field with single quote, risking unauthorized infrastructure configuration and security breaches."
regex = '''(?i)(?:administrator_login_password|password)(?:[0-9a-z\-_\t .]{0,20})(?:[\s|']|[\s|"]){0,3}(?:=|>|:{1,3}=|\|\|:|<=|=>|:|\?=)(?:'|\"|\s|=|\x60){0,5}('[a-z0-9=_\-]{8,20}')(?:['|\"|\n|\r|\s|\x60|;]|$)'''
keywords = [
    "administrator_login_password","password",
]