name: gitleaks-test

on:
  workflow_dispatch:

jobs:
  gitleaks-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the gitleaks
        run: |
          VERSION=$(curl -s "https://api.github.com/repos/gitleaks/gitleaks/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")' | sed 's/^v//')
          wget "https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz"
          tar xzvf gitleaks_${VERSION}_linux_x64.tar.gz -C /usr/local/bin
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Make test files
        run: bun run src/index.ts
      - name: Detect leaks
        run: gitleaks detect -v --no-git -s . -f sarif -r gitleaks-test-report.sarif
      - name: Upload leaks results
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-test-report.sarif
          category: gitleaks-test-result
